### ISSUE TITLE
void function error

### ISSUE THREAD

**Issue by rhoit** [io12/org-fragtog#1]
I'm using emacs 26.3 with org-mode 9.1.9 version, I get *void-function error*, do i need to upgrade the version any thing close I could find was [org-version-issue](https://emacs.stackexchange.com/questions/49055/org-mode-9-2can-t-find-the-error-on-my-dot-emacs)

```
Org-Fragtog mode enabled in current buffer
Error in post-command-hook (org-fragtog--post-cmd): (void-function org-clear-latex-preview)
Quit
Making completion list...
```

**Comment by io12** [comment]
`org-clear-latex-preview` was added in a newer version of org-mode. The latest version is 9.3.2.

**Comment by io12** [comment]
You can get the latest version from org ELPA. https://orgmode.org/elpa.html

**Comment by io12** [comment]
I added this info to the README in https://github.com/io12/org-fragtog/commit/141320b9a64e5cb94374e033ddc534f2419cf4cc.

Unfortunately, I can't figure out a way to make this work reliably with older Org versions.

**Comment by rhoit** [comment]
now I'm using emacs 28 with org 9.3.2, too much changes at last it works!

**Comment by io12** [comment]
Thank you for trying `org-fragtog`!
