### ISSUE TITLE
Not working with org-journal

### ISSUE THREAD

**Issue by marlinstrub** [io12/org-fragtog#10]
I really enjoy this, thanks for your effort to make this into a package other people can use!

It doesn't work with [org-journal](https://github.com/bastibe/org-journal) buffers, any idea what could be going wrong?

**Comment by io12** [comment]
Thanks for reporting the issue! It seems like org-journal-mode is a major mode derived from org-mode. My package checks to make sure it's being run in an org-mode buffer and that apparently doesn't include org-journal buffers. I pushed a fix that checks for derived modes too.

**Comment by marlinstrub** [comment]
Awesome, works like a charm. Thanks for the quick fix.
