### ISSUE TITLE
Can org-fragtog work in programming buffers in places where org-latex-preview works?

### ISSUE THREAD

**Issue by darcamo** [io12/org-fragtog#11]
I just started using org-fragtog in org-mode buffers and it is really great.

I often add latex equations to python docstrings and I can see them just fine with `org-latex-preview`. It would be nice to have org-fragtog also working in python docstrings.

Is it feasible to extend it to work in places where `org-latex-preview` already works?

**Comment by io12** [comment]
Thanks for the suggestion! Fixed in commit https://github.com/io12/org-fragtog/commit/99ba1b8661eaccdce5a279820231d61ce6f9d7da.
