### ISSUE TITLE
File mode specification error: (void-function org-fragtog-mode) under Org mode version 9.3.7

### ISSUE THREAD

**Issue by dylanhogan** [io12/org-fragtog#12]
Hi -- thanks for the extension. I'm having trouble getting this to work using spacemacs & Org mode version 9.3.7, receiving the following void-function error: 
```
File mode specification error: (void-function org-fragtog-mode)
```
Org fragments work normally using `C-c C-x C-l`. Please let me know if you have potential solutions in mind. Thanks!

**Comment by io12** [comment]
I'm also using spacemacs and Org 9.3.7, and it works for me. Based on the error, my guess is `org-fragtog` isn't installed? For spacemacs, you need to add `org-fragtog` to `dotspacemacs-additional-packages`. Hope this helps.

**Comment by dylanhogan** [comment]
Ah – adding `org-fragtog` to `dotspacemacs-additional-packages` did the trick. Apologies for the basic question, I'm new to spacemacs in general. Thanks very much for your help!
