### ISSUE TITLE
[Feature request]Org table support

### ISSUE THREAD

**Issue by failable** [io12/org-fragtog#13]
Hi, thanks for the awesome package.

I wonder if the package can support '[previewing](https://www.reddit.com/r/emacs/comments/d3a8or/pretty_org_tables_in_the_buffer_chapter_2_it/)' org tables for better table display.

**Comment by io12** [comment]
This is a good idea. Thanks for the feature request!

**Comment by io12** [comment]
After looking into that Reddit thread, I think table previews are probably outside the scope of `org-fragtog`. It would be really cool as a separate package or a built-in `org-mode` feature, though.

**Comment by Yevgnen** [comment]
Try this: https://github.com/Yevgnen/org-fragtog-table
