### ISSUE TITLE
Variable to turn off automatic toggling while being in a table

### ISSUE THREAD

**Issue by WhatDothLife** [io12/org-fragtog#15]
Hi, dank package! It'd be nice, if there were a variable to tune, so that org-frag-tog ignores tables. The proportions are messed up by previews. Thx

**Comment by io12** [comment]
That's a good idea and yeah I've run into the same problem. Probably it's a good idea to generalize this to a `org-fragtog-deny-list`, a list of predicate functions for denying things that can be checked with functions. So for tables it would be `(add-hook 'org-fragtog-deny-list 'org-at-table-p)`.

**Comment by io12** [comment]
Fixed with https://github.com/io12/org-fragtog/commit/2270f906034c94ad696821a1b05811d72ce19457
