### ISSUE TITLE
feature request: display all expressions as rendered when first visiting buffer

### ISSUE THREAD

**Issue by holtzermann17** [io12/org-fragtog#19]
@io12 I think what the poster in #9 meant was (paraphrasing):

> Would it be possible to add a command to rerender all LaTeX expressions in the buffer, so that I can add that to my `org-mode-hook`?

At the level of implementation, perhaps it's also possible to cache the images somewhere, so that they aren't actually rerendered but simply re-inserted in the buffer.

I think it's a good feature request!

**Comment by io12** [comment]
Thanks. After rereading #9's post, I think you're right. Org-mode already supports this with `org-startup-with-latex-preview` and caches the images in `org-preview-latex-image-directory`. Hopefully this is good enough and doesn't warrant a new org-fragtog feature.

**Comment by holtzermann17** [comment]
Yep, perfect! I'd suggest a quick note about this feature in the README to spread awareness.

**Comment by holtzermann17** [comment]
Also, if anyone wants to toggle all of the images this exists as well, but is a bit hidden.

- `(org-latex-preview '(16))` turns them on
- `(org-latex-preview '(64))` turns them off

There doesn't seem to be a variable making the state (on or off) explicit from a programmatic standpoint.
