### ISSUE TITLE
Latex Preview problem

### ISSUE THREAD

**Issue by hehao9504** [io12/org-fragtog#20]
I am not sure the problem is introduced by fragtog or my configuration. Please help to check, Thank you~
When I type $\to$, it seems include some extra configuration detail 
<img width="1148" alt="Screenshot 2021-02-25 下午9 18 09" src="https://user-images.githubusercontent.com/8615461/109161273-d1572c80-77b1-11eb-8d11-19403245c3e1.png">
While I type $A \to \lambda$, it is OK
<img width="112" alt="Screenshot 2021-02-25 下午9 40 10" src="https://user-images.githubusercontent.com/8615461/109161502-18ddb880-77b2-11eb-94bd-e08d42ccb3aa.png">

**Comment by io12** [comment]
I don't think this is an issue with org-fragtog, because it just uses org-mode's built-in fragment functionality. Anyway, when I try your example, it works okay for me. Out of curiosity, what values do you have for `org-preview-latex-default-process` and `org-preview-latex-process-alist`?

**Comment by hehao9504** [comment]
here is my code

```elisp
(setq org-preview-latex-default-process 'dvisvgm)
(setq org-preview-latex-process-alist
       '((dvipng :programs
         ("lualatex" "dvipng")
         :description "dvi > png" :message "you need to install the programs: latex and dvipng." :image-input-type "dvi" :image-output-type "png" :image-size-adjust
         (1.0 . 1.0)
         :latex-compiler
         ("lualatex -output-format dvi -interaction nonstopmode -output-directory %o %f")
         :image-converter
         ("dvipng -fg %F -bg %B -D %D -T tight -o %O %f"))
       (dvisvgm :programs
          ("latex" "dvisvgm")
          :description "dvi > svg" :message "you need to install the programs: latex and dvisvgm." :use-xcolor t :image-input-type "xdv" :image-output-type "svg" :image-size-adjust
          (1.7 . 1.5)
          :latex-compiler
          ("xelatex -no-pdf -interaction nonstopmode -output-directory %o %f")
          :image-converter
          ("dvisvgm %f -n -b min -c %S -o %O"))
       (imagemagick :programs
              ("latex" "convert")
              :description "pdf > png" :message "you need to install the programs: latex and imagemagick." :use-xcolor t :image-input-type "pdf" :image-output-type "png" :image-size-adjust
              (1.0 . 1.0)
              :latex-compiler
              ("xelatex -no-pdf -interaction nonstopmode -output-directory %o %f")
              :image-converter
              ("convert -density %D -trim -antialias %f -quality 100 %O"))))
```

**Comment by hehao9504** [comment]
It seems this issue is related with my configuration. I clean my configuration and reinstall doom, now it is OK. Thank you for your reply.
BTW: org-fragtog is so amazing. I can enjoy latex typing and elegant preview in my org file again. :)
