### ISSUE TITLE
when new fragment is rendered, adjacent window redisplays

### ISSUE THREAD

**Issue by holtzermann17** [io12/org-fragtog#21]
In the screenshots below:

The right-hand window has an Org Mode buffer in it; the left-hand window has a PDF in it.  When fragtog renders a *new* fragment, the PDF on the left redisplays and recentres to the top of the page. (This disrupts my editing workflow when I have the PDF positioned so I can read the text on the bottom of the page!)

![Screenshot-2021-03-07,20:57:54](https://user-images.githubusercontent.com/179958/110254654-ed17bb00-7f87-11eb-9aae-166ceaa1d61d.png)
![Screenshot-2021-03-07,20:58:00](https://user-images.githubusercontent.com/179958/110254652-ec7f2480-7f87-11eb-82b7-72d59ff4cbcd.png)

**Comment by io12** [comment]
Thanks for your issue. I haven't used any PDF preview pane for org-mode before, so how can I reproduce this? What are you using to redisplay the PDF?

**Comment by io12** [comment]
@holtzermann17 any updates on this?

**Comment by io12** [comment]
Going to close this for inactivity. Feel free to reopen the issue if you still have this problem.
