### ISSUE TITLE
Upstream the feature to mainline org mode?

### ISSUE THREAD

**Issue by shenlebantongying** [io12/org-fragtog#31]
Do you consider upstream the code to org mode and make it a default?

I think upstreaming this feature has some benefits, like 

* ppl no long have to google "how to toggle org-latex". Finding tweaks or packages online always wastes time. 
* extra helps from org maintainers?
* More users may enjoy it without even know it if this become default :)

**Comment by io12** [comment]
I can try to do this.

**Comment by shenlebantongying** [comment]
I use Emacs but dislike the Emacs community in general now.

Emacs is too extensible & hackable. Everyone has their own bag of hacks instead of considering the common good.

Having this functionality in a separate package is the way of emacs.

Upstreaming this is considered against the common practice.
