### ISSUE TITLE
Preview is not displayed as I type

### ISSUE THREAD

**Issue by chrt** [io12/org-fragtog#32]
Suppose that I type $e^x$. No preview is generated as I finish the second $. If I then move the cursor inside the formula, and then move it outside the formula, the preview is generated correctly.

Is this the intended behavior? What to do if I want to see the preview as I finish typing, without moving my cursor in and out?

Thank you!

**Comment by io12** [comment]
This isn't intended behavior and I'm kind of confused how nobody else noticed this before now. I guess most people type both `$` first, then move the cursor inside and enter the formula, or maybe an org-mode update caused the bug somehow. Anyway, thanks! I will work on fixing this.

**Comment by io12** [comment]
This should be fixed now. Thanks again!
