### ISSUE TITLE
Add math-preview as a backend

### ISSUE THREAD

**Issue by deb75** [io12/org-fragtog#34]
Hello,

Is it possible to add [math-preview](https://gitlab.com/matsievskiysv/math-preview) as a backend for svg's generation ?

This feature request is related to an opened request [here](https://gitlab.com/matsievskiysv/math-preview/-/issues/9#note_805876746)

Regards

**Comment by io12** [comment]
I haven't tried math-preview, but does the code in [this comment](https://github.com/io12/org-fragtog/pull/22#issuecomment-836056382) work?

```emacs-lisp
(defalias #'org-latex-preview #'math-preview-at-point)
(defalias #'org-clear-latex-preview #'math-preview-clear-region)
```

If this is enough, maybe I can add it to the README or math-preview can add it to its README.

**Comment by deb75** [comment]
Yes, it works :-) and I can tell it is much more faster than the `dvisvgm` backend

Probably, the best way should be to add an entry to `org-preview-latex-process-alist`, e.g. `'mathjax` and set it with `(setq org-preview-latex-default-process 'mathjax)`. But it does not seem compatible at first view or I am not skilled enough.

**Comment by deb75** [comment]
With the following settings :
```
(defalias #'org-latex-preview #'math-preview-at-point)
(defalias #'org-clear-latex-preview #'math-preview-clear-region)
```
math-preview replaces the current backend of org-fragtog.
It works well except when equation is indented :

```
\begin{equation}
x^2
\end{equation}
```
works, but
```
    \begin{equation}
    x^2
    \end{equation}
```
does not work.

Of course, it still works if I invoke `math-preview-at-point` by hand.

I asked [this question](https://gitlab.com/matsievskiysv/math-preview/-/issues/11) to `math-preview` maintainer. According to him, it does not seem to be `math-preview` related.

Do you experience the same issue ?

Regards

**Comment by io12** [comment]
It looks like this happens because org-mode considers whitespace before a LaTeX fragment as part of the fragment, but `math-preview-at-point` doesn't. There is already code to discard whitespace after the fragment, so probably the solution is for `org-fragtog` to try toggling at the end of the fragment instead of the beginning.

**Comment by deb75** [comment]
Hello,

I still experience this issue, is there a simple way to do what you propose. I guess one of `org-fragtog`'s forks did something close with this [commit](https://github.com/rka97/org-fragtog/commit/6fcbc01c5d598c259b7c64ff73c0a51c6c7c4367).

But I do not know yet if it works

Regards

EDIT : I do not think it works, but it is true that if I remove all the space before the first line of latex environment,
usually it is `\begin{...`, then `org-fragtog` works well with `math-preview`.

When there is some space, `org-fragtog` correctly finds the latex fragments and disable it when the cursor hovers the latex
fragment, but `org-fragtog` will never enable it again.

**Comment by io12** [comment]
Fixed with https://github.com/io12/org-fragtog/commit/e69fb119a7ef3dc39381edd66a20dce9d384fffd. Sorry I didn't get to it until now.
