### ISSUE TITLE
Equation numbering

### ISSUE THREAD

**Issue by deb75** [io12/org-fragtog#35]
Hello,

I am not sure it is a question for `org-fragtog` itself.

The equation environment in latex usually comes with a numbering.

The org latex preview does display this number but always with the same number (1),
probably because each equation is processed independently of others.

Should there be a way to improve this ? For example, by making org latex preview count
previous equation environments, except if they come with a `*`, before the current one ?

Regards

**Comment by io12** [comment]
Hi. This is about `org-mode` itself and not `org-fragtog`, but it looks like there are some good suggestions here https://stackoverflow.com/questions/26090651/emacs-org-mode-increment-equation-numbers-with-latex-preview
