### ISSUE TITLE
‘org-element-property’ is not known to be defined.

### ISSUE THREAD

**Issue by Samoed** [io12/org-fragtog#36]
Hi. When running package-install got.
```
In end of data:
org-fragtog.el:227:1:Warning: the function ‘org-element-property’ is not knownto be defined
```
When I write in org this works, but after restarting emacs (doom) it can't find it. 

```
emacs        27.2
doom         21.12.0-alpha HEAD -> master, origin/master c7753adb
```

**Comment by io12** [comment]
With Doom Emacs, you aren't supposed to use `M-x package-install`. Information for package management in Doom can be found [here](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#package-management).

It should be enough to add
```lisp
(package! org-fragtog)
```
to `packages.el` and
```lisp
(use-package! org-fragtog
  :hook (org-mode . org-fragtog-mode))
```
to `config.el`.

Let me know if this solves your issue.

**Comment by Samoed** [comment]
That's work. Thank you.
