### ISSUE TITLE
Small preview

### ISSUE THREAD

**Issue by SeungheonOh** [io12/org-fragtog#37]
**Describe the bug**
In macos, it is showing me an absurdly small preview.

**To Reproduce**
Macos, any latex fragment

**Expected behavior**
bigger preview 

**Videos**
https://user-images.githubusercontent.com/24271442/151044284-7e7386f5-6ba2-4723-aaec-78ec6997c317.mov

**Version and environment**
GNU Emacs 28.0.90 (build 1, aarch64-apple-darwin21.1.0, NS appkit-2113.00 Version 12.0.1 (Build 21A559)) of 2021-12-31

**Comment by io12** [comment]
Does adding this to your config fix it?
```lisp
(plist-put org-format-latex-options :scale 2)
```

You can change the `2` to something else to adjust the size.

**Comment by SeungheonOh** [comment]
Oh didn't know there was an option for that. I'll check that this evening.

**Comment by SeungheonOh** [comment]
Great, it worked!
Might be a good idea to add it do a documentation...
