### ISSUE TITLE
Toggle Entire Line

### ISSUE THREAD

**Issue by ninjaguppy** [io12/org-fragtog#38]
**Describe the solution you'd like**
I would love it if all of the fragments on the current line were toggled instead of only the fragments under the cursor. That way when you move to a new line you can see all of the relevant latex code but the entire line re-toggles upon leaving the line. I'm not sure how difficult this would be to implement I figured it would be worth a suggestion!

**Additional context**
Back when I used vim, one of my favorite packages was [tex-conceal](https://github.com/KeitaNakamura/tex-conceal.vim) which provides very similar functionality.

**Comment by wosined** [comment]
I never used tex-conceal, but it looks more similar to [prettifying](https://www.gnu.org/software/auctex/manual/auctex/Prettifying.html) than previewing.

**Comment by ninjaguppy** [comment]
I was able to get something similar working with prettying---thanks!
