### ISSUE TITLE
How do I install and load your package in emacs?

### ISSUE THREAD

**Issue by viogp** [io12/org-fragtog#41]
Hi,

This package seems great but as I cannot see your package within the available list in emacs I'd like more details on how to 'install and load'.

What I do within emacs:
‘M-x package-list-packages’

In my .emacs I have the following lines:

(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                     ("marmalade" . "http://marmalade-repo.org/packages/")
                     ("melpa" . "http://melpa.org/packages/")))
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
(when (not package-archive-contents)
  (package-refresh-contents))

Thanks in advance

**Comment by io12** [comment]
Thanks for the interest in the package. The [MELPA Install Guide](https://melpa.org/#/getting-started) says to call `(package-initialize)` right after setting `package-archives`.

```el
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")))
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))
```

Let me know whether this works.

**Comment by jncrenshaw** [comment]
If you're using [straight.el](https://github.com/radian-software/straight.el) with the `straight-use-package` function, you can use this:
`(straight-use-package 'org-fragtog)`
And to enable it when org-mode is started:
`(add-hook 'org-mode-hook 'org-fragtog-mode)`

I have both in my init.el file.

**Comment by viogp** [comment]
Thanks for your replies. What @io12 said worked, however it seems I have a too old version of emacs and to change it is not as trivial a simple update.
`org-fragtog is an incompatible package.

     Status: Incompatible because it depends on Emacs 27.1.
    Archive: melpa
    Version: 20220110.2211
     Commit: 680606189d5d28039e6f9301b55ec80517a24005
    Summary: Auto-toggle Org LaTeX fragments
   Requires: emacs-27.1
   Homepage: https://github.com/io12/org-fragtog
`

**Comment by io12** [comment]
> it seems I have a too old version of emacs and to change it is not as trivial a simple update

How old is your Emacs version? If it's so old that updating breaks your config then it might not be possible to get a modern version of org-mode running.

**Comment by viogp** [comment]
hahahaha, not that old! I've org-mode and org-roam working :)

26.3

![image](https://user-images.githubusercontent.com/20089252/171354711-6bbd6f30-f370-44c7-a729-f4674791a6e6.png)

I'll try to come around to update to 27 in the coming months, but since this requires reinstallation I need to find a block of quiet time.
