### ISSUE TITLE
Do not support chinese?

### ISSUE THREAD

**Issue by sincebyte** [io12/org-fragtog#42]
**Describe the bug**
$$ P\{\mbox{拒绝} \mid H_{0} \mbox{为真}\} = \alpha $$
I expect to display chinese chars . but the result is chinese chars are not show int the org mode.

**Comment by imakira** [comment]
I think it isn't this package's problem.
You may refer to [this thread](https://emacs-china.org/t/topic/6507/8).

**Comment by io12** [comment]
> I think it isn't this package's problem. You may refer to [this thread](https://emacs-china.org/t/topic/6507/8).

I agree that it probably isn't an org-fragtog bug. Thanks for linking the thread!
