### ISSUE TITLE
Error in post-command-hook (org-fragtog--post-cmd): (error "Invalid format character: ‘%B’")

### ISSUE THREAD

**Issue by jinlin82** [io12/org-fragtog#7]
I can't get this to work. The error:

`Error in post-command-hook (org-fragtog--post-cmd): (error "Invalid format character: ‘%B’")`

Emacs version: GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13
org mode version: Org mode version 9.3.6 (9.3.6-17-g389288-elpa @ ./.emacs.d/elpa/org-20200224/)

Thanks.

**Comment by io12** [comment]
Do org fragments work normally for you with `C-c C-x C-l`? If not, do you get a similar error?

**Comment by io12** [comment]
Going to close this issue. Feel free to re-open it if you still have problems.
